insert into Universidad values('Universidad Nacional de Lanús') 
insert into Universidad values('Universidad Nacional de Avellaneda') 
insert into Universidad values('Universidad de Buenos Aires')
insert into Universidad values('Universidad Tecnólogica Nacional') 

insert into Carrera values('Licenciatura en Sistemas') 
insert into Carrera values('Licenciatura en Tecnologías Ferroviarias')
insert into Carrera values('Enfermería') 
insert into Carrera values('Arquitectura') 
insert into Carrera values('Ingeniería Informática')
insert into Carrera values('Analista de Sistemas') 
insert into Carrera values('Medicina')
insert into Carrera values('Ingeniería Textil') 

insert into UniversidadCarrera values (1, 1)
insert into UniversidadCarrera values (1, 2)
insert into UniversidadCarrera values (1, 3)
insert into UniversidadCarrera values (2, 3)
insert into UniversidadCarrera values (2, 4)
insert into UniversidadCarrera values (2, 5)
insert into UniversidadCarrera values (3, 3)
insert into UniversidadCarrera values (3, 4)
insert into UniversidadCarrera values (3, 5)
insert into UniversidadCarrera values (3, 6)
insert into UniversidadCarrera values (3, 7)
insert into UniversidadCarrera values (4, 1)
insert into UniversidadCarrera values (4, 8)

insert into Materia values('Programación')
insert into Materia values('Matemática 1')
insert into Materia values('Arquitectura de computadoras')
insert into Materia values('Introducción al pensamiento científico')
insert into Materia values('Fisica 1')
insert into Materia values('Quimica 1')
insert into Materia values('Anatomía')
insert into Materia values('Farmacología')
insert into Materia values('Sistemas de representación')
insert into Materia values('Administración de proyectos')
insert into Materia values('Nutrición')
insert into Materia values('Termodinámica')

insert into CarreraMateria values (1, 1)
insert into CarreraMateria values (1, 2)
insert into CarreraMateria values (1, 3)
insert into CarreraMateria values (1, 4)
insert into CarreraMateria values (2, 2)
insert into CarreraMateria values (2, 5)
insert into CarreraMateria values (2, 6)
insert into CarreraMateria values (3, 6)
insert into CarreraMateria values (3, 7)
insert into CarreraMateria values (3, 8)
insert into CarreraMateria values (4, 2)
insert into CarreraMateria values (4, 5)
insert into CarreraMateria values (4, 9)
insert into CarreraMateria values (5, 1)
insert into CarreraMateria values (5, 2)
insert into CarreraMateria values (5, 3)
insert into CarreraMateria values (5, 5)
insert into CarreraMateria values (6, 1)
insert into CarreraMateria values (6, 2)
insert into CarreraMateria values (6, 3)
insert into CarreraMateria values (6, 4)
insert into CarreraMateria values (6, 10)
insert into CarreraMateria values (7, 4)
insert into CarreraMateria values (7, 6)
insert into CarreraMateria values (7, 7)
insert into CarreraMateria values (7, 11)
insert into CarreraMateria values (8, 2)
insert into CarreraMateria values (8, 5)
insert into CarreraMateria values (8, 12)

insert into TipoUsuario values('Estudiante')
insert into TipoUsuario values('Profesor')
insert into TipoUsuario values('Administrador')

/* estudiantes */

insert into Usuario values('Alvaro', 'Alba', '39000111', 'estudiante1@unla.com', 1234, 1)
insert into Usuario values('Ariel', 'Aragon', '39000112', 'estudiante2@unla.com', 1234, 1)
insert into Usuario values('Ana', 'Alvarez', '39000113', 'estudiante3@unla.com', 1234, 1)
insert into Usuario values('Aldana', 'Ayala', '39000114', 'estudiante4@unla.com', 1234, 1)
insert into Usuario values('Aldo', 'Arcoiris', '39000115', 'estudiante5@unla.com', 1234, 1)
insert into Usuario values('Brian', 'Bolañes', '39000116', 'estudiante1@undav.com', 1234, 1)
insert into Usuario values('Bartolomeo', 'Bala', '39000117', 'estudiante2@undav.com', 1234, 1)
insert into Usuario values('Barbara', 'Billar', '39000118', 'estudiante3@undav.com', 1234, 1)
insert into Usuario values('Carlos', 'Caceres', '39000119', 'estudiante1@uba.com', 1234, 1)
insert into Usuario values('Cintia', 'Caceres', '39000120', 'estudiante2@uba.com', 1234, 1)
insert into Usuario values('Cecilio', 'Cardoso', '39000121', 'estudiante3@uba.com', 1234, 1)
insert into Usuario values('Cecilia', 'Cardoso', '39000122', 'estudiante4@uba.com', 1234, 1)
insert into Usuario values('Cristopher', 'Col', '39000123', 'estudiante5@uba.com', 1234, 1)
insert into Usuario values('Dario', 'Duende', '39000124', 'estudiante1@utn.com', 1234, 1)
insert into Usuario values('Delia', 'Dud', '39000125', 'estudiante2@utn.com', 1234, 1)

insert into UsuarioCarreraUniversidad values(1, 1, 1)
insert into UsuarioCarreraUniversidad values(2, 1, 1)
insert into UsuarioCarreraUniversidad values(3, 1, 1)
insert into UsuarioCarreraUniversidad values(4, 2, 1)
insert into UsuarioCarreraUniversidad values(5, 3, 1)
insert into UsuarioCarreraUniversidad values(6, 3, 2)
insert into UsuarioCarreraUniversidad values(7, 4, 2)
insert into UsuarioCarreraUniversidad values(8, 5, 2)
insert into UsuarioCarreraUniversidad values(9, 3, 3)
insert into UsuarioCarreraUniversidad values(10, 4, 3)
insert into UsuarioCarreraUniversidad values(11, 5, 3)
insert into UsuarioCarreraUniversidad values(12, 6, 3)
insert into UsuarioCarreraUniversidad values(13, 7, 3)
insert into UsuarioCarreraUniversidad values(14, 1, 4)
insert into UsuarioCarreraUniversidad values(15, 8, 4)

insert into UsuarioMateria values(1, 1)
insert into UsuarioMateria values(1, 2)
insert into UsuarioMateria values(1, 3)
insert into UsuarioMateria values(1, 4)
insert into UsuarioMateria values(2, 1)
insert into UsuarioMateria values(2, 2)
insert into UsuarioMateria values(3, 4)
insert into UsuarioMateria values(4, 2)
insert into UsuarioMateria values(4, 5)
insert into UsuarioMateria values(4, 6)
insert into UsuarioMateria values(5, 6)
insert into UsuarioMateria values(5, 7)
insert into UsuarioMateria values(5, 8)
insert into UsuarioMateria values(6, 2)
insert into UsuarioMateria values(6, 5)
insert into UsuarioMateria values(6, 9)
insert into UsuarioMateria values(7, 1)
insert into UsuarioMateria values(7, 2)
insert into UsuarioMateria values(7, 3)
insert into UsuarioMateria values(7, 5)
insert into UsuarioMateria values(8, 6)
insert into UsuarioMateria values(8, 7)
insert into UsuarioMateria values(9, 7)
insert into UsuarioMateria values(10, 9)
insert into UsuarioMateria values(10, 2)
insert into UsuarioMateria values(11, 1)
insert into UsuarioMateria values(11, 2)
insert into UsuarioMateria values(12, 10)
insert into UsuarioMateria values(12, 2)
insert into UsuarioMateria values(13, 6)
insert into UsuarioMateria values(13, 7)
insert into UsuarioMateria values(13, 8)
insert into UsuarioMateria values(13, 11)
insert into UsuarioMateria values(13, 4)
insert into UsuarioMateria values(14, 1)

/* profesores */

insert into Usuario values('Pedro', 'Perez', '14000111', 'profesor1@email.com', 1234, 2)
insert into Usuario values('Patricio', 'Perez', '14000112', 'profesor2@email.com', 1234, 2)
insert into Usuario values('Paul', 'Palmieri', '14000113', 'profesor3@email.com', 1234, 2)
insert into Usuario values('Pablo', 'Piñon', '14000114', 'profesor4@email.com', 1234, 2)
insert into Usuario values('Pascual', 'Perico', '14000115', 'profesor5@email.com', 1234, 2)
insert into Usuario values('Paula', 'Pardo', '14000116', 'profesor6@email.com', 1234, 2)
insert into Usuario values('Patricia', 'Pozo', '14000117', 'profesor7@email.com', 1234, 2)
insert into Usuario values('Paola', 'Pinzón', '14000118', 'profesor8@email.com', 1234, 2)
insert into Usuario values('Pilar', 'Perez', '14000119', 'profesor9@email.com', 1234, 2)
insert into Usuario values('Paris', 'Penoso', '14000120', 'profesor10@email.com', 1234, 2)
insert into Usuario values('Paz', 'Pinto', '14000121', 'profesor11@email.com', 1234, 2)

insert into UsuarioCarreraUniversidad values(16, 1, 1)
insert into UsuarioCarreraUniversidad values(16, 1, 4)
insert into UsuarioCarreraUniversidad values(17, 2, 1)
insert into UsuarioCarreraUniversidad values(18, 3, 1)
insert into UsuarioCarreraUniversidad values(18, 3, 2)
insert into UsuarioCarreraUniversidad values(19, 1, 1)
insert into UsuarioCarreraUniversidad values(19, 6, 3)
insert into UsuarioCarreraUniversidad values(19, 7, 3)
insert into UsuarioCarreraUniversidad values(19, 1, 4)
insert into UsuarioCarreraUniversidad values(20, 1, 1)
insert into UsuarioCarreraUniversidad values(20, 2, 1)
insert into UsuarioCarreraUniversidad values(21, 5, 2)
insert into UsuarioCarreraUniversidad values(21, 5, 3)
insert into UsuarioCarreraUniversidad values(22, 4, 2)
insert into UsuarioCarreraUniversidad values(22, 4, 3)
insert into UsuarioCarreraUniversidad values(23, 6, 3)
insert into UsuarioCarreraUniversidad values(24, 7, 3)
insert into UsuarioCarreraUniversidad values(24, 3, 3)
insert into UsuarioCarreraUniversidad values(25, 8, 4)
insert into UsuarioCarreraUniversidad values(25, 1, 4)
insert into UsuarioCarreraUniversidad values(26, 8, 4)

insert into UsuarioMateria values(16,1)
insert into UsuarioMateria values(16,3)
insert into UsuarioMateria values(17,5)
insert into UsuarioMateria values(17,6)
insert into UsuarioMateria values(17,2)
insert into UsuarioMateria values(18,6)
insert into UsuarioMateria values(18,7)
insert into UsuarioMateria values(18,8)
insert into UsuarioMateria values(19,4)
insert into UsuarioMateria values(20,2)
insert into UsuarioMateria values(21,5)
insert into UsuarioMateria values(21,2)
insert into UsuarioMateria values(21,1)
insert into UsuarioMateria values(21,3)
insert into UsuarioMateria values(22,5)
insert into UsuarioMateria values(22,2)
insert into UsuarioMateria values(22,9)
insert into UsuarioMateria values(23,2)
insert into UsuarioMateria values(23,1)
insert into UsuarioMateria values(23,3)
insert into UsuarioMateria values(23,10)
insert into UsuarioMateria values(24,6)
insert into UsuarioMateria values(24,7)
insert into UsuarioMateria values(24,8)
insert into UsuarioMateria values(24,11)
insert into UsuarioMateria values(25,2)
insert into UsuarioMateria values(25,1)
insert into UsuarioMateria values(25,3)
insert into UsuarioMateria values(26,12)
insert into UsuarioMateria values(26,5)

insert into Usuario values('Nick', 'Fury', '12000111', 'administrador1@email.com', 1234, 3)

insert into Idioma values('Español')
insert into Idioma values('Inglés')
insert into Idioma values('Portugues')
insert into Idioma values('Aleman')
