// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnlaLibrary.Data.Context;

namespace UnlaLibrary.Data.Migrations
{
    [DbContext(typeof(Library))]
    [Migration("20210520044056_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCarrera")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Carrera1")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("carrera");

                    b.HasKey("IdCarrera");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.CarreraMateria", b =>
                {
                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("idMateria");

                    b.HasKey("IdCarrera", "IdMateria");

                    b.HasIndex("IdMateria");

                    b.ToTable("CarreraMateria");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Idioma", b =>
                {
                    b.Property<int>("IdIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idIdioma")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Idioma1")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("idioma");

                    b.HasKey("IdIdioma");

                    b.ToTable("Idioma");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMateria")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Materia1")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Materia");

                    b.HasKey("IdMateria");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.MaterialEstudio", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Archivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("archivo");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("autor");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdIdioma")
                        .HasColumnType("int")
                        .HasColumnName("idIdioma");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("idMateria");

                    b.Property<int>("IdUniversidad")
                        .HasColumnType("int")
                        .HasColumnName("idUniversidad");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<byte[]>("Miniatura")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("miniatura");

                    b.Property<string>("Prologo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("prologo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("titulo");

                    b.HasKey("IdMaterial");

                    b.HasIndex("IdIdioma");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdUniversidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MaterialEstudio");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Reseña", b =>
                {
                    b.Property<int>("IdReseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReseña")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("comentario");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("idMaterial");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int")
                        .HasColumnName("puntuacion");

                    b.HasKey("IdReseña");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reseña");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoUsuario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombreTipoUsuario");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Universidad", b =>
                {
                    b.Property<int>("IdUniversidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUniversidad")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreUniversidad")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombreUniversidad");

                    b.HasKey("IdUniversidad");

                    b.ToTable("Universidad");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UniversidadCarrera", b =>
                {
                    b.Property<int>("IdUniversidad")
                        .HasColumnType("int")
                        .HasColumnName("idUniversidad");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.HasKey("IdUniversidad", "IdCarrera");

                    b.HasIndex("IdCarrera");

                    b.ToTable("UniversidadCarrera");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("apellido");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("clave");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idTipoUsuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UsuarioCarreraUniversidad", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<int>("IdUniversidad")
                        .HasColumnType("int")
                        .HasColumnName("idUniversidad");

                    b.HasKey("IdUsuario", "IdCarrera", "IdUniversidad");

                    b.HasIndex("IdCarrera");

                    b.HasIndex("IdUniversidad");

                    b.ToTable("UsuarioCarreraUniversidad");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UsuarioMateria", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int")
                        .HasColumnName("idMateria");

                    b.HasKey("IdUsuario", "IdMateria");

                    b.HasIndex("IdMateria");

                    b.ToTable("UsuarioMateria");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.CarreraMateria", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.Carrera", "IdCarreraNavigation")
                        .WithMany("CarreraMateria")
                        .HasForeignKey("IdCarrera")
                        .HasConstraintName("FK_CarreraMateria_Carrera")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Materia", "IdMateriaNavigation")
                        .WithMany("CarreraMateria")
                        .HasForeignKey("IdMateria")
                        .HasConstraintName("FK_CarreraMateria_Materia")
                        .IsRequired();

                    b.Navigation("IdCarreraNavigation");

                    b.Navigation("IdMateriaNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.MaterialEstudio", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.Idioma", "IdIdiomaNavigation")
                        .WithMany("MaterialEstudio")
                        .HasForeignKey("IdIdioma")
                        .HasConstraintName("FK_MaterialEstudio_Idioma")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Materia", "IdMateriaNavigation")
                        .WithMany("MaterialEstudio")
                        .HasForeignKey("IdMateria")
                        .HasConstraintName("FK_MaterialEstudio_Materia")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Universidad", "IdUniversidadNavigation")
                        .WithMany("MaterialEstudio")
                        .HasForeignKey("IdUniversidad")
                        .HasConstraintName("FK_MaterialEstudio_Universidad")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("MaterialEstudio")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_MaterialEstudio_Usuario")
                        .IsRequired();

                    b.Navigation("IdIdiomaNavigation");

                    b.Navigation("IdMateriaNavigation");

                    b.Navigation("IdUniversidadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Reseña", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.MaterialEstudio", "IdMaterialNavigation")
                        .WithMany("Reseña")
                        .HasForeignKey("IdMaterial")
                        .HasConstraintName("FK_Reseña_MaterialEstudio")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("Reseña")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Reseña_Usuario")
                        .IsRequired();

                    b.Navigation("IdMaterialNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UniversidadCarrera", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.Carrera", "IdCarreraNavigation")
                        .WithMany("UniversidadCarrera")
                        .HasForeignKey("IdCarrera")
                        .HasConstraintName("FK_UniversidadCarrera_Carrera")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Universidad", "IdUniversidadNavigation")
                        .WithMany("UniversidadCarrera")
                        .HasForeignKey("IdUniversidad")
                        .HasConstraintName("FK_UniversidadCarrera_Universidad")
                        .IsRequired();

                    b.Navigation("IdCarreraNavigation");

                    b.Navigation("IdUniversidadNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Usuario", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.TipoUsuario", "IdTipoUsuarioNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("IdTipoUsuario")
                        .HasConstraintName("FK_Usuario_TipoUsuario")
                        .IsRequired();

                    b.Navigation("IdTipoUsuarioNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UsuarioCarreraUniversidad", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.Carrera", "IdCarreraNavigation")
                        .WithMany("UsuarioCarreraUniversidad")
                        .HasForeignKey("IdCarrera")
                        .HasConstraintName("FK_UsuarioCarreraUniversidad_Carrera")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Universidad", "IdUniversidadNavigation")
                        .WithMany("UsuarioCarreraUniversidad")
                        .HasForeignKey("IdUniversidad")
                        .HasConstraintName("FK_UsuarioCarreraUniversidad_Universidad")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioCarreraUniversidad")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_UsuarioCarreraUniversidad_Usuario")
                        .IsRequired();

                    b.Navigation("IdCarreraNavigation");

                    b.Navigation("IdUniversidadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.UsuarioMateria", b =>
                {
                    b.HasOne("UnlaLibrary.Data.Entities.Materia", "IdMateriaNavigation")
                        .WithMany("UsuarioMateria")
                        .HasForeignKey("IdMateria")
                        .HasConstraintName("FK_UsuarioMateria_Materia")
                        .IsRequired();

                    b.HasOne("UnlaLibrary.Data.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioMateria")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_UsuarioMateria_Usuario")
                        .IsRequired();

                    b.Navigation("IdMateriaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Carrera", b =>
                {
                    b.Navigation("CarreraMateria");

                    b.Navigation("UniversidadCarrera");

                    b.Navigation("UsuarioCarreraUniversidad");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Idioma", b =>
                {
                    b.Navigation("MaterialEstudio");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Materia", b =>
                {
                    b.Navigation("CarreraMateria");

                    b.Navigation("MaterialEstudio");

                    b.Navigation("UsuarioMateria");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.MaterialEstudio", b =>
                {
                    b.Navigation("Reseña");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.TipoUsuario", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Universidad", b =>
                {
                    b.Navigation("MaterialEstudio");

                    b.Navigation("UniversidadCarrera");

                    b.Navigation("UsuarioCarreraUniversidad");
                });

            modelBuilder.Entity("UnlaLibrary.Data.Entities.Usuario", b =>
                {
                    b.Navigation("MaterialEstudio");

                    b.Navigation("Reseña");

                    b.Navigation("UsuarioCarreraUniversidad");

                    b.Navigation("UsuarioMateria");
                });
#pragma warning restore 612, 618
        }
    }
}
