using ConsoleApp1.Context;
using System;
using System.IO;

namespace ConsoleApp1
{
    public class Program
    {
         static void Main(string[] args)
        {
           using(var c = new Library())
            {
                string path1 = Directory.GetCurrentDirectory();
                var n = path1.IndexOf("\\ConsoleApp1\\bin\\Debug\\netcoreapp3.1");
                string dir = path1.Substring(0, n);

                Byte[] bytes = File.ReadAllBytes(string.Format("{0}\\kernighan-and-ritchie.pdf",dir));
                String file = Convert.ToBase64String(bytes);
                Byte[] bytesP = File.ReadAllBytes(string.Format("{0}\\portada.png",dir));
                Byte[] bytesP2 = File.ReadAllBytes(string.Format("{0}\\portada2.jpg", dir));
                Byte[] bytesP3 = File.ReadAllBytes(string.Format("{0}\\portada3.jpg", dir));
                Byte[] bytesP4 = File.ReadAllBytes(string.Format("{0}\\portada4.png", dir));
                Byte[] bytesP5 = File.ReadAllBytes(string.Format("{0}\\portada5.jpg", dir));
                Byte[] bytesP6 = File.ReadAllBytes(string.Format("{0}\\portada6.jpg", dir));
                Byte[] bytesP7 = File.ReadAllBytes(string.Format("{0}\\portada7.jpg", dir));
                Byte[] bytesP8 = File.ReadAllBytes(string.Format("{0}\\portada8.jpg", dir));
                Byte[] bytesP9 = File.ReadAllBytes(string.Format("{0}\\portada9.jpg", dir));
                Byte[] bytesP10 = File.ReadAllBytes(string.Format("{0}\\portada10.jpg", dir));

                //c.MaterialEstudio.Add(new Entities.MaterialEstudio {Titulo = "Fundamentos de programación",  Descripcion = "descripcion 1",Prologo ="prologo1", Autor="autor 1", IdIdioma=1,IdUsuario=3, IdMateria=1,IdUniversidad=1,Archivo =bytes, Miniatura=bytesP });
                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "El lenguaje de programación", Descripcion = "Este es uno de los primeros libros que debemos leer (probablemente incluso más de una vez) para poder empezar a ser buenos programadores", Prologo = "Este es uno de los requisitos más solicitados por las empresas a la hora de optar a un puesto de trabajo. Clean Code, o código limpio, es un libro que nos enseña la filosofía del buen programador. Un libro con todo tipo de técnicas para facilitar y optimizar tanto la lectura como la escritura de código. Un código limpio ayuda a ahorrar mucho tiempo en la labor de depuración, solución de errores y mejoras del programa. Este libro, de Anaya, nos enseña todas las posibilidades que nos ofrece este lenguaje de programación. Con él podremos empezar a programar prácticamente desde cero, y seguir ampliando nuestros conocimientos dominando las librerías y bibliotecas, así como sus funciones más avanzadas. Una guía tanto para iniciados como para expertos.", Autor = "Kernighan R.", IdIdioma = 1, IdUsuario = 16, IdMateria = 1, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Arquitectura de computadoras", Descripcion = "El presente manual está destinado a personas con conocimientos básicos sobre computadoras", Prologo = "La arquitectura de computadoras es el diseño conceptual y la estructura operacional fundamental de un sistema de computadoras.1​Es decir, es un modelo y una descripción funcional de los requerimientos y las implementaciones de diseño para varias partes de una computadora, con especial interés en la forma en que la unidad central de proceso (CPU) trabaja internamente y accede a las direcciones de memoria. También la arquitectura del computador está basado en tres grandes principios que se aplican a todo dispositivo o componente del computador, estos tres principios son: velocidad, capacidad y tipo de conexión.También suele definirse como la forma de interconectar componentes de hardware, para crear computadoras según los requerimientos de funcionalidad, rendimiento y costo. La computadora recibe y envía la información a través de los periféricos, por medio de los canales. La CPU es la encargada de procesar la información que le llega a la computadora. El intercambio de información se tiene que hacer con los periféricos y la CPU. Puede considerarse que todas aquellas unidades de un sistema, exceptuando la CPU, se denomina periférico, por lo que la computadora tiene dos partes bien definidas.", Autor = "Behrooz Parmani", IdIdioma = 1, IdUsuario = 16, IdMateria = 3, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP2 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Matematica básica", Descripcion = "El libro Introducción a la Matemática hace parte de un curso de ingreso a las universidades argentinas.", Prologo = "ELas matemáticas o la matemática2​ (del latín mathematĭca, y este del griego μαθηματικά, transliterado como mathēmatiká, derivado de μάθημα, tr. máthēma. 'conocimiento') es/son una ciencia formal que, partiendo de axiomas y siguiendo el razonamiento lógico, estudia/n las propiedades, estructuras abstractas y relaciones entre entidades abstractas como números, figuras geométricas, iconos, glifos o símbolos en general.La matemática es un conjunto de lenguajes formales que pueden usarse como herramienta para plantear problemas en contextos específicos. Por ejemplo, el siguiente enunciado puede expresarse de dos formas: X es mayor que Y y Y es mayor que Z, o en forma simplificada puede decirse que X > Y > Z. Este es el motivo por el cual las matemáticas son tan solo un lenguaje simplificado con una herramienta para cada problema específico (por ejemplo, 2 x 2 = 4 o bien 2 + 2 = 4).", Autor = "Camila Cortes", IdIdioma = 1, IdUsuario = 17, IdMateria = 2, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP3 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Manual de pensamiento científico", Descripcion = "Es un primer acercamiento a cuestiones, términos y debates que los estudiantes van a tratar en profundidad en otras asignaturas", Prologo = "El pensamiento científico es un modo de razonamiento inaugurado por la aparición de las ciencias modernas. Se basa en el escepticismo, la observación y la experimentación, es decir, en la comprobación demostrable de las interpretaciones que hacemos del mundo y de las leyes que lo rigen. Entre las principales características del pensamiento científico se encuentran la objetividad (se toman los hechos tal y como se presentan en la realidad), la racionalidad (parte de principios y leyes científicas) y la sistematicidad (el conocimiento es ordenado y jerarquizado). El sentido común, ofrece explicaciones sin demostraciones críticas que destaquen la relevancia de la explicación, para los hechos que intenta aclarar.", Autor = "Amos Granjales", IdIdioma = 1, IdUsuario = 17, IdMateria = 4, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP4 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Fundamentos de programación", Descripcion = "Un lenguaje de programación es un lenguaje que puede ser utilizado para controlar el comportamiento de una máquina, particularmente una computadora", Prologo = "Para crear un programa, y que la computadora lo interprete y ejecute, las instrucciones deben escribirse en un lenguaje de programación. En sus comienzos las computadoras interpretaban solo instrucciones en un lenguaje específico, del más bajo nivel, conocido como código máquina, siendo éste excesivamente complicado para programar. De hecho solo consiste en cadenas de números 1 y 0 (sistema binario). Para facilitar el trabajo de programación, los primeros científicos, que trabajaban en el área, decidieron reemplazar las instrucciones, secuencias de unos y ceros, por mnemónicos, que son abreviaturas en inglés de la función que cumple la instrucción; las codificaron y crearon así un lenguaje de mayor nivel, que se conoce como Assembly o lenguaje ensamblador. Por ejemplo, para sumar se podría usar la letra A de la palabra inglesa add (sumar). En realidad escribir en lenguaje ensamblador es básicamente lo mismo que hacerlo en lenguaje máquina, pero las letras y palabras son bastante más fáciles de recordar y entender que secuencias de números binarios. A medida que la complejidad de las tareas que realizaban las computadoras aumentaba, se hizo necesario disponer de un método más sencillo para programar.", Autor = "Luis Joyanes", IdIdioma = 1, IdUsuario = 16, IdMateria = 1, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP5 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Fundamentos de programación JAVA", Descripcion = "Java es un lenguaje de programación y una plataforma informática que fue comercializada por primera vez en 1995 por Sun Microsystems. ", Prologo = "Hay muchas aplicaciones y sitios web que no funcionarán, probablemente, a menos que tengan Java instalado y cada día se crean más. Java es rápido, seguro y fiable. Desde ordenadores portátiles hasta centros de datos, desde consolas para juegos hasta computadoras avanzadas, desde teléfonos móviles hasta Internet, Java está en todas partes, si es ejecutado en una plataforma no tiene que ser recompilado para correr en otra. Java es, a partir de 2012, uno de los lenguajes de programación más populares en uso, particularmente para aplicaciones de cliente-servidor de web, con unos diez millones de usuarios reportados. El lenguaje de programación Java fue desarrollado originalmente por James Gosling, de Sun Microsystems (constituida en 1983 y posteriormente adquirida el 27 de enero de 2010 por la compañía Oracle),4​ y publicado en 1995 como un componente fundamental de la plataforma Java de Sun Microsystems. Su sintaxis deriva en gran medida de C y C++, pero tiene menos utilidades de bajo nivel que cualquiera de ellos. Las aplicaciones de Java son compiladas a bytecode (clase Java), que puede ejecutarse en cualquier máquina virtual Java (JVM) sin importar la arquitectura de la computadora subyacente.", Autor = "Ricardo Billalobos", IdIdioma = 1, IdUsuario = 16, IdMateria = 1, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP6 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "El libro de la física", Descripcion = "Ciencia que estudia las propiedades de la materia y de la energía y establece las leyes que explican los fenómenos naturales ", Prologo = "La física es tal vez la más antigua de todas las disciplinas académicas, ya que la astronomía es una de sus subdisciplinas. También comenzó hace más de dos mil años con los primeros trabajos de filósofos griegos. En los últimos dos milenios, la física fue considerada parte de lo que ahora llamamos filosofía, química y ciertas ramas de la matemática y la biología, pero durante la Revolución Científica en el siglo XVII se convirtió en una ciencia moderna, única por derecho propio. Sin embargo, en algunas esferas como la física matemática y la química cuántica, los límites de la física con otras ramas de la ciencia siguen siendo difíciles de distinguir. La formulación de las teorías sobre las leyes que gobiernan el Universo ha sido un objetivo central de la física desde tiempos remotos, con la filosofía del empleo sistemático de experimentos cuantitativos de observación y prueba como fuente de verificación. La clave del desarrollo histórico de la física incluye hitos como la ley de la gravitación universal y la mecánica clásica de Newton.", Autor = "Watson Margenau", IdIdioma = 1, IdUsuario = 17, IdMateria = 5, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP7 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Chemistry", Descripcion = "Science that studies the properties of matter and energy and establishes the laws that explain natural phenomena", Prologo = "Physics is perhaps the oldest of all academic disciplines, as astronomy is one of its sub-disciplines. It also began more than two thousand years ago with the first works of Greek philosophers. In the last two millennia, physics was considered part of what we now call philosophy, chemistry, and certain branches of mathematics and biology, but during the Scientific Revolution in the 17th century it became a modern science, unique in its own right. However, in some spheres such as mathematical physics and quantum chemistry, the limits of physics with other branches of science remain difficult to distinguish. The formulation of theories about the laws that govern the Universe has been a central objective of physics since ancient times, with the philosophy of the systematic use of quantitative observation and testing experiments as a source of verification. The key to the historical development of physics includes milestones such as the law of universal gravitation and classical Newtonian mechanics.", Autor = "Watson Margenau", IdIdioma = 2, IdUsuario = 17, IdMateria = 6, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP8 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "Organic Chemistry", Descripcion = "Now that science studies the properties of matter and energy and establishes the laws that explain natural phenomena", Prologo = "Physics is perhaps the oldest of all academic disciplines, as astronomy is one of its sub-disciplines. It also began more than two thousand years ago with the first works of Greek philosophers. In the last two millennia, physics was considered part of what we now call philosophy, chemistry, and certain branches of mathematics and biology, but during the Scientific Revolution in the 17th century it became a modern science, unique in its own right. However, in some spheres such as mathematical physics and quantum chemistry, the limits of physics with other branches of science remain difficult to distinguish. The formulation of theories about the laws that govern the Universe has been a central objective of physics since ancient times, with the philosophy of the systematic use of quantitative observation and testing experiments as a source of verification. The key to the historical development of physics includes milestones such as the law of universal gravitation and classical Newtonian mechanics.", Autor = " George Linconln", IdIdioma = 2, IdUsuario = 17, IdMateria = 6, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP9 });

                c.MaterialEstudio.Add(new Entities.MaterialEstudio { Titulo = "El gran libro del cuerpo humano",  Descripcion = "Este libro da una introducción a todo lo necesario para la formación de futuros profesionales en la ciencia de la salud del cuerpo humano", Prologo = "La anatomía humana es la ciencia de carácter práctico y morfológico que se dedica principalmente al estudio de las estructuras macroscópicas del cuerpo humano.1​ Deja el estudio de los tejidos a la histología, y el de las células a la citología y a la biología celular. La anatomía humana es una ciencia especial dentro de la anatomía general animal.Biológicamente,el ser humano es un animal.Y, como los animales, el cuerpo humano se organiza, mediante una visión sistemática y a semejanza del Universo del que forma parte, en diferentes niveles de jerarquización que, enlistados en orden ascendente(de lo micro a lo macro, de lo más invisible e interno hacia lo más visible y externo), son los siguientes: se compone de moléculas, que juntas se vuelven células, y estas dependiendo de su tipo se vuelven a su vez tejidos, y estos a su vez se clasifican en órganos, para finalmente por conjuntos y función se denominen aparatos, y estos integrados formen sistemas.Otras visiones(funcional, morfogenética, clínica, etcétera), según otros criterios, estudian el cuerpo humano desde otras perspectivas, pero esta es la que suele utilizarse para comprender lo básico.", Autor = "Alice Roberts", IdIdioma = 1, IdUsuario = 18, IdMateria = 7, IdUniversidad = 1, Archivo = bytes, Miniatura = bytesP10 });
       
                c.SaveChanges();
                
            }

        }
    }
}
